# Config for Magic by cosmicnebula200

# for internal purposes please dont change
version: 1.0.0

# Tag item id
# default is 421 (nametag)
item-id: 421

# Tag Name
# {tag_name} is the one sus tag ok
item-name: "&l&c{tag_name} &r&bTag"

# Tag Lore
item-lore:
  - "&cright click to claim your {tag_name} tag"

form-title: "&l&Magic&dTags"

# Database structure
# DO NOT MESS WITH THIS IF YOU DONT KNOW WHAT YOU DOIN
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: magictags.sql
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: tags
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1
